### ISSUE TITLE
The condition vector is missed in the Coordinate Generator part in Figure 3.

### ISSUE THREAD

**Issue by Yutong-Zhou-cv** [yizhiwang96/TextLogoLayout#3]
Hi Yizhi, thanks a lot for making the code publicly available for this nice work. 
I just noticed a little mistake: The Coordinate Generator takes the condition vector and a random noise as inputs; however, the condition vector seems to be missing from Figure 3(in [arxiv paper](https://arxiv.org/pdf/2204.02701.pdf)). 
Best regards.

**Comment by yizhiwang96** [comment]
Hi Yutong,
Thanks for your question!
It was denoted as "Condition Feat." in Figure 3. "Condition Vector" is another name when I refered it as a sequence (f_{1}^{c}, f_{2}^{c}, ..., f_{N}^{c}). 
Sorry for the inconsistent names.

**Comment by Yutong-Zhou-cv** [comment]
Thank you very much for your patient reply.
As you mentioned, the inputs of the Coordinate Generator are "Condition Feat." and random noise. That would make sense.
Thanks again for your pretty work, and I look forward to generating original text logo layouts from custom input texts in the near future~
